# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 301a96b3ce1f47be00db2c72e40c90072afed9878f40fd3fcd3421b0ddb99918b4206749c8adaff57cc91abe03fdc4e864617a0284dd2f8513e1e127a086d970

test:
  secret_key_base: b831740c61c1a36103c7d5d2e4acc302c3fce32ce4e7eaba62c65abdd4546ed525ee72b4056885ad76682c3bdf77794cdd8d410479b92cc17a2b46e9393ae6fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
